### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by kamiyaa** [sboli/twmn#31]
I tried a $ make and it gave me this:
$ make
cd twmnd/ && make -f Makefile
make[1]:Entering directory '/home/shana/builds/twmn/twmnd'
g++ -c -pipe -Wall -Werror -pedantic -Wno-long-long -g -Wall -W -D_REENTRANT -DQT_NO_DEBUG_OUTPUT -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDbus -I/usr/include/qt4 -I, -o main.o main.cpp
main.cpp:11:38: error: 'QMessageLogContext' does not name a type
 void logOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                                                ^
main.cpp:11:58: error: ISO C++ forbids declaration of 'context' with no type [-fpermission]
 void logOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                                                                                       ^
main.cpp: In function 'int main(int, char*_)':
main.cpp:40:37: error: 'qInstallMessageHandler' was not declared in this scope
     qInstallMessageHandler(logOutput);
                                                            ^
Makefile:254: recipe for target 'main.o' failed
make[1]: *_\* [main.o] Error
make[1]: Leaving directory '/home/shana/builds/twmn/twmnd'
Makefile:40: recipe for targget 'sub-twmnd-make_default' failed
make: **\* [sub-twmnd-make_default] Error 2

**Comment by stilllife00** [comment]
Same here, even with qt5 on Ubuntu

    mirko@mirkobuntu ~/apps/twmn (master)$ qmake -v
    QMake version 3.0
    Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

    mirko@mirkobuntu ~/apps/twmn (master)$ qmake

    mirko@mirkobuntu ~/apps/twmn (master)$ make
    cd twmnd/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mirko/apps/twmn/twmnd/twmnd.pro -o Makefile ) && make -f Makefile 
    make[1]: Entering directory `/home/mirko/apps/twmn/twmnd'
    g++ -c -m64 -pipe -Wall -Werror -pedantic -Wno-long-long -g -Wall -W -D_REENTRANT -DQT_NO_DEBUG_OUTPUT -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -o main.o main.cpp
    main.cpp:11:38: error: ‘QMessageLogContext’ does not name a type
    void logOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                      ^
    main.cpp:11:58: error: ISO C++ forbids declaration of ‘context’ with no type [-fpermissive]
    void logOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
                                                          ^
    main.cpp: In function ‘int main(int, char**)’:
    main.cpp:40:37: error: ‘qInstallMessageHandler’ was not declared in this scope
     qInstallMessageHandler(logOutput);
                                     ^
    make[1]: *** [main.o] Error 1
    make[1]: Leaving directory `/home/mirko/apps/twmn/twmnd'
    make: *** [sub-twmnd-make_first] Error 2

**Comment by lunchboxer** [comment]
I'm experiencing the same situation, installed qt5 packages mentioned above and getting same error

**Comment by lunchboxer** [comment]
I managed to make it past the above error by simply rewriting the Makefiles. I'm now at level 2 with the following error:

cd twmnd/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/james/twmn/twmnd/twmnd.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/james/twmn/twmnd'
g++ -c -m64 -pipe -Wall -Werror -pedantic -Wno-long-long -g -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o main.o main.cpp
g++ -c -m64 -pipe -Wall -Werror -pedantic -Wno-long-long -g -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o widget.o widget.cpp
widget.cpp:21:32: fatal error: QtX11Extras/QX11Info: No such file or directory
 #include <QtX11Extras/QX11Info>
                                ^
compilation terminated.
Makefile:347: recipe for target 'widget.o' failed
make[1]: *** [widget.o] Error 1
make[1]: Leaving directory '/home/james/twmn/twmnd'
Makefile:39: recipe for target 'sub-twmnd-make_first' failed
make: *** [sub-twmnd-make_first] Error 2

I can't find any reference to "QtX11Extras/QX11Info" on the webs

**Comment by lunchboxer** [comment]
Linux 3.16.0-44-generic Ubuntu 14.10 x86_64

**Comment by daryltucker** [comment]
`libqt5x11extras5-dev` is the Deban package that provides the QtX11Extras libraries.  The build also needs `libboost-all-dev`, vs `libboost-dev`.
