### ISSUE TITLE
How does shortcuts work?

### ISSUE THREAD

**Issue by simendsjo** [sboli/twmn#32]
Seems that commit a076bd13bb56da3671b8b029210f94939d68a2de removed grabbing the keyboard to handle shortcuts. How should I add shortcuts myself now? Creating a small program to see if a notification is visible and calling `twmnc --remote` seems quite overkill.

**Comment by simendsjo** [comment]
Any update on this?

**Comment by sboli** [comment]
Sorry, since migration to Qt5 shorcuts are no longer supported. I will see if I have time to work on this.
In the meantime you can use xbindkeys and twmnc --remote in order to send your shortcuts.

**Comment by cincodenada** [comment]
I already use xbindkeys for things like making my volume buttons work, so that works great for me.  For those who are interested, here are the relevant lines from my config (using hjkl for prev/hide/activate/next, use `xbindkeys -mk` to find your own key combos):

    "twmnc --remote next"
    Control+Shift + l

    "twmnc --remote previous"
        Control+Shift + h

    "twmnc --remote activate"
        Control+Shift + k

    "twmnc --remote hide"
        Control+Shift + j

**Comment by naphthalene** [comment]
This can probably be closed - its cleaner to have the desktop manager/window manager handle grabbing they key and invoking `twmnc --remote <command>`. Thanks for your comment @cincodenada, helped me out.
