### ISSUE TITLE
openbox autostart

### ISSUE THREAD

**Issue by worenga** [sboli/twmn#38]
Hi,
i like twmn its a cool tool.

However, when i put twmnd in my openbox `autostart` file like this 

```
twmnd &
```

it will ignore my settings in `~/.config/twmn/twmn.conf`and fall back to the default settings, however i figured when i simply say 

```
twmnd 
```

it will use the config file from my home directory as expected. This seems counterintuitive.
At first i thought this was some kind of rights issue so i chmod 777 the config file, but that didnt help.
Lubuntu 14.10, master branch

**Comment by CraftThatBlock** [comment]
This is probably because it's running `twmnd` as root, and not your user account, hence not looking for the right config (sorry it this is too late!)

You could fix this with:

`su - charles -c "twmnd &"`

And replace `charles` with your use account (can be found with `whoami`)
