### ISSUE TITLE
Repackage twmn for AUR4

### ISSUE THREAD

**Issue by seanrand** [sboli/twmn#41]
With the release of AUR4, the twmn package is no longer available in the AUR.

**Comment by sboli** [comment]
Great. I merged your request.
I don't have that much free time, that's a good idea. I made you Collaborator, meaning you can push to the repo.

**Comment by seanrand** [comment]
I figure your comment was supposed to be on #42. Closing this as @CraftThatBlock uploaded the package to AUR4.

**Comment by CraftThatBlock** [comment]
Thanks :)

I'll try my best to maintain the package on AUR and here if there's any major issues (that I can fix)
