### ISSUE TITLE
twmnd consumes ~5‰ cpu while idling

### ISSUE THREAD

**Issue by l29ah** [sboli/twmn#43]

**Comment by CraftThatBlock** [comment]
Do you have any additional info? It runs at about 0.0% for my system (checked using htop)

**Comment by l29ah** [comment]
Check out the TIME column in htop.

**Comment by CraftThatBlock** [comment]
Can you give me some of _your_ results?

**Comment by l29ah** [comment]
Huh? I see it incrementing by ~20ms every few seconds, hence the topic.

**Comment by CraftThatBlock** [comment]
Sorry, I can't reproduce anything you are saying sadly, my TIME for twmnd is 0:00.14 after about an hour of uptime.

Can you try to give me more information? Thanks.

**Comment by l29ah** [comment]
On Sun, Aug 30, 2015 at 04:47:16PM -0700, Charles-William Crete wrote:
> Sorry, I can't reproduce anything you are saying sadly, my TIME for twmnd is 0:00.14 after about an hour of uptime.
> 
> Can you try to give me more information? Thanks.

Okay, i've fired up strace and see twmnd reacting on every modkey press, every mouse button press and every window manager key binding press. Like this:

[pid 26381] <... poll resumed> )        = 1 ([{fd=3, revents=POLLIN}])
[pid 26381] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"U\2z\1\21\257\326\1\3@@\0\0\0\0\0\0\0\0@@@@@\0\0\3\37\205\2\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
[pid 26381] write(5, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 26378] <... poll resumed> )        = 1 ([{fd=5, revents=POLLIN}])
[pid 26381] <... write resumed> )       = 8
[pid 26378] read(5,  <unfinished ...>
[pid 26381] poll([{fd=3, events=POLLIN}], 1, 4294967295 <unfinished ...>
[pid 26378] <... read resumed> "\1\0\0\0\0\0\0\0", 16) = 8
[pid 26378] poll([{fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=10, events=POLLIN}], 4, 4294967295 <unfinished ...>

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by CraftThatBlock** [comment]
That's very unusual, I can't really help you thought, as I have no idea what would cause this to use that much CPU.
