### ISSUE TITLE
overlapping arguments

### ISSUE THREAD

**Issue by Link-Satonaka** [sboli/twmn#44]
"-f" doesn't work, and "--foreground" also does not work.

"--forgroun" as listed by the help, works. It would seem there is a spelling error not only in the help output, but also in the code itself.

**Comment by Link-Satonaka** [comment]
None of the color arguments work at the moment, color can only be set by config file

**Comment by Link-Satonaka** [comment]
Upon closer inspection, there are a lot of problems with the arguments.
-p refers to both 'port' and 'position'
-f refers to 'font', 'font-size' and 'foregroun'
-a refers to 'always-on-top' and 'activated-command'

**Comment by CraftThatBlock** [comment]
Fixed https://github.com/sboli/twmn/commit/8f8989442b7e40b95d29387b9ad5990b349be18d
