### ISSUE TITLE
notification does not disappear for "out_animation_duration < 2"

### ISSUE THREAD

**Issue by breunigs** [sboli/twmn#49]
At least, with `out_animation=13`, the `out_animation_duration` needs to be at least 2ms or higher. I assume with these incredibly short amounts, the animation cannot be played and twmn returns early, leaving the most recent notification there forever.

This is regardless of settings for bounce and/or in_animation.

**Comment by sboli** [comment]
Fixed. Added a lower limit of 30 ms. Which is already not perceptible.
