### ISSUE TITLE
I am unable to disable bounce

### ISSUE THREAD

**Issue by ShawnMcCool** [sboli/twmn#52]
It seems that twmnd picks up my changes for font etc.. But, the bounce is still there when I call `twmnc You have connected.`.

[twmn.conf](https://gist.github.com/ShawnMcCool/609734ebcfe8ba0b8cdd200c224b81ad)

Am I overlooking something?

**Comment by ixjlyons** [comment]
The `bounce` configuration options correspond to transitions between notifications, so you won't see the effect for single notifications. However, see the [QEasingCurve enum](http://doc.qt.io/qt-5/qeasingcurve.html#EasingFunction-typedef) -- 38 corresponds to the `OutBounce` curve.

**Comment by sboli** [comment]
What @ixjlyons said is correct. Closed.
