### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by philenotfound** [sboli/twmn#54]
Hi, was trying to package twmn but haven't found anything resembling a version number.
Have I overlooked it?

**Comment by sboli** [comment]
No version number. Just grab the git HEAD and you're good to go.

**Comment by philenotfound** [comment]
I want to create a Debian package so a version number is really nice.

**Comment by sboli** [comment]
Version number added. You can see it by running the command twmnc.
Current version : 1.2
