### ISSUE TITLE
Text in italics?

### ISSUE THREAD

**Issue by mrkgnao** [sboli/twmn#61]
The screenshot in the readme uses italic text. How can I get this in my own notifications?

**Comment by sboli** [comment]
Just use html.So for html : 

<i>My italic text</i>

**Comment by mrkgnao** [comment]
Oddly enough, when I tried it earlier, it didn't work. Is there a reference for what HTML I can use here?

**Comment by sboli** [comment]
There you go : You can use any html code I think.
List will be truncated though.

**Comment by mrkgnao** [comment]
Well, in fact, I realised what had happened. If I write to the twmn socket from a Python script, I have to manually escape the `<i>` tags. I just did it on a whim and it worked.

**Comment by sboli** [comment]
Nice.
