### ISSUE TITLE
[Security] Listening on public address instead of localhost

### ISSUE THREAD

**Issue by Profpatsch** [sboli/twmn#71]
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp6       0      0 :::9797                 :::*                                1273/twmnd          
```

The daemon listens not only on localhost (`::1`), but on all addresses (`::`)!

**Comment by sboli** [comment]
You can change the host parameter under the main section in the configuration file to only allow listening on localhost

**Comment by Profpatsch** [comment]
Wait, what?

That’s not how a notification daemon should work!
