### ISSUE TITLE
Using Sound in twmnc

### ISSUE THREAD

**Issue by astralspurs** [sboli/twmn#82]
Hi there,

I'm trying to put together a simple timer app that dings when a timer has elapsed.

I've tried using the twmnc flag, i.e.:
`twmnc -t "$msg" -c "$duration minutes have passed" -sc "mpv ~/path/to/sfx.aac"`

I've also looked at the "sound_command=" option in twmn.conf, but to not avail. I'm just looking for some more guidance to use sound features in twmn as I haven't been able to find any docs that talk about this.

Thanks for your help.

**Comment by sboli** [comment]
That's exactly how you should proceed. Don't forget to escape the path in the command, as such:
`--sc "mpv \"/some/path/file.ext\"."`
