### ISSUE TITLE
Build fails (deprecated functions)

### ISSUE THREAD

**Issue by Wrexes** [sboli/twmn#85]
Hey,
I can't get the package to build, either from the AUR (using yay) or manually from here. I'm getting deprecated function warnings and they'retreated as errors -- which cause make to abort.
Here's my [build log](https://github.com/sboli/twmn/files/3651002/build_log.txt).

**Comment by Penguin-Guru** [comment]
Your build log is somewhat different from mine, but I got around this by making with CXXFLAGS="-Wno-error=deprecated-declarations". Also needed -fPIC.
